#! /bin/bash

# https://www.reddit.com/r/bash/comments/k7vz1o/comment/gexkxz4/

# NOTE: be really fucking careful running this. shit randomly fails sometimes
# but i dont really need this anymore to figure out why

source $HOME/.shell_colors

startingDir=$PWD
while IFS= read -rd '' file; do
  files+=( "$file" )
  artist=${PWD##*/}
  artist=${artist%%/*}
  album=${PWD##*/}
  title=${files[-1]##*/}
  printf "${YELLOW} ---------------------------------${NOCOL}\n"
  printf "${BLUE}artist: $artist${NOCOL}\n"
  echo "album: $album"
  echo "adding data to: $title"
  echo "---------------------------------"
done < <(find "$startingDir" -maxdepth 1 -type f -print0)

while IFS= read -rd '' file1; do
  dirArray+=( "${file1}" )
  cd "${dirArray[-1]}"
  artist=${PWD##*$startingDir/}
  artist=${artist%%/*}
  while IFS= read -rd '' file2; do
    width=$(tput cols)
    subfiles+=( "${file2}" )
    album=${dirArray[-1]##*/}
    title=${subfiles[-1]##*/}
    printf ${YELLOW}%0${width}s|tr \  -${NOCOL}
    printf "${PURPLE}${UNDERLINE}adding data to:${NOCOL} $title\n"
    printf "${BLUE}${UNDERLINE}artist:${NOCOL} $artist\n"
    printf "${BLUE}${UNDERLINE}album:${NOCOL} $album\n"
    printf "${GREEN}...${NOCOL}"
    ffmpeg -hide_banner -nostats -loglevel warning -y -i "$file1/$title" -c copy\
     -metadata artist="$artist"\
     -metadata album_artist="$artist"\
     -metadata album="$album"\
     -metadata title="$title"\
     "$file1/meta-${title}"
    mv "$file1/meta-${title}" "$file1/$title"
    printf "${GREEN}done${NOCOL}\n"
    printf ${YELLOW}%0${width}s|tr \  -${NOCOL}
    echo; echo
  done < <(find "$PWD" -maxdepth 1 -type f -print0)
done < <(find "$startingDir" -type d -print0)
