#! /bin/bash

cd $HOME
#Check for mounted external drives
#mounted=$( lsblk | dmenu -l 10 -p "Select:" | awk '{print $7}' )

#if [[ -n $mounted ]]; then
#	echo External Drive Mounted, Continuing...
#else
#	mountables=$( $1 | sudo fdisk -l | grep -v nvme | grep -v Disk | grep dev | awk '{print $1}' | dmenu -l 5 -p "Select Drive To Mount:" )
#	sudo mount -o umask=022,gid=1000,uid=1000 $mountables /run/mount/
#fi

##Delete unnecessary directories for backup
rm -r $HOME/.thumbnails/
rm -r $HOME/.cache/

##Perform the sync

# Home directory of laptop
rsync -av --exclude=music --exclude=pictures --exclude=documents /home/tom /run/media/tom/easystore/backup/laptop/
notify-send -u normal -t 6000 "Home Folder Backup Complete"

# Media from laptop to collective media directories on backup
#This is deprecated, I only sync music from my main machine which is always the most up to date. 
#rsync -av $HOME/music /run/media/tom/easystore/backup/
#notify-send -u normal -t 6000 "Music Folder Backup Complete"
rsync -av $HOME/pictures /run/media/tom/easystore/backup/
#notify-send -u normal -t 6000 "Pictures Folder Backup Complete"

# Documents from laptop to collective documents directory on backup
rsync -av $HOME/documents /run/media/tom/easystore/backup/
#notify-send -u normal -t 6000 "Coffee Directory Backup Complete"



