#! /bin/bash 

cd $HOME
#Check for mounted external drives
#mounted=$( lsblk | dmenu -l 10 -p "Select:" | awk '{print $7}' )
#
#if [[ -n $mounted ]]; then
#	echo External Drive Mounted, Continuing...
#else
#	mountables=$( $1 | sudo fdisk -l | grep -v nvme | grep -v Disk | grep dev | awk '{print $1}' | dmenu -l 5 -p "Select Drive To Mount:" )
#	sudo mount -o umask=022,gid=1000,uid=1000 $mountables /run/mount/
#fi

#Delete unnecessary directories for backup
rm -r $HOME/.thumbnails/
rm -r $HOME/.cache/

## Perform the sync

# Home directory of desktop
rsync -av --exclude=music --exclude=pictures /home/tom /run/media/tom/easystore/backup/desktop/
notify-send -u normal -t 6000 "Home Folder Backup Complete" 

# Media from desktop to collective media directories on backup
rsync -av $HOME/music /run/media/tom/easystore/backup/
notify-send -u normal -t 6000 "Music Backup Complete"
rsync -av $HOME/pictures /run/media/tom/easystore/backup/
notify-send -u normal -t 6000 "Pictures Backup Complete"

# Documents from desktop to collective documents directory on backup
rsync -av $HOME/documents /run/media/tom/easystore/backup/
notify-send -u normal -t 6000 "Documents Backup Complete"
