#! /bin/bash

# A battery alarm for polybar

bat_capac=$(cat /sys/class/power_supply/BAT0/capacity)
discharging=$(cat /sys/class/power_supply/BAT0/status)

if [ $bat_capac -le 15 -a $discharging == "Discharging" ]; then
	echo "Your battery is low!"
else
	echo ""
fi

if [ $bat_capac -le 5 -a $discharging == "Discharging" ]; then
	( speaker-test -t sine -f 1000 )& pid=$! ; sleep 0.2s ; kill -9 $pid
#	notify-send "Battery below 5%!"
fi
