#! /bin/bash

# A simple battery-level script for i3bar

[[ $(acpi -b | awk '!/Unknown/{print $3}') == "Discharging," ]] && \
	[[ "$(acpi -b | awk '!/Unknown/{print $4}' | tr -d \%,)" -le "100" ]] && echo suspend && exit 1

if [ "$(ls /sys/class/power_supply)" ]; then
	echo $batCapac && echo "blank"
	[[ $(acpi -b | awk '!/Unknown/{print $3}') == "Discharging," ]] && echo "#ff0000" || echo "#e89709"
else
	echo
fi
