#! /bin/bash

# A simple battery-level script for i3bar
# If there is no battery (i.e. desktop) nothing is output

if [ "$(ls /sys/class/power_supply)" ]; then
	echo `acpi -b | awk '!/Unknown/{print $2$4}' | tr -d ,` && echo "blank"
	[[ $(acpi -b | awk '!/Unknown/{print $3}') == "Discharging," ]] && echo "#ff0000" || echo "#33cc33"
else
	echo
fi
