#! /bin/bash

# Brightness value
outFile="/sys/class/backlight/radeon_bl0/brightness"
lvl=$( cat $outFile )
num='^[0-9]+$'

# Echo the appropriate newly incremented brightness level into $lvl depending on the argument passed when calling this
# script (see i3 config media keys section)

# Check if input is a specific number, if true set to specific value (%).
if [[ $1 =~ $num ]]; then
	lvl=$( echo "$1*255/100" | bc ) 
	echo "$lvl" > $outFile
else
	if [ $1 == "up" ]; then
		lvl=$(( $lvl + 25 ))
		if [ $lvl -le 255 ]; then
			echo "$lvl" > $outFile
		else
			lvl=255
			echo $lvl > $outFile
		fi
	else
		lvl=$(( $lvl - 25 ))
		if [ $lvl -ge 0 ]; then
			echo "$lvl" > $outFile
		else
			lvl=0
			echo "$lvl" > $outFile
		fi
	fi
fi

lvlPercent=$( echo "$lvl/255*100" | bc -lq )
lvlPercent="${lvlPercent%.*}%"
notify-send -u low -t 150 "$lvlPercent"
