#! /bin/bash

# grep the pacman log for errors from today's run
warnings=$(grep warning: /var/log/pacman.log | grep `date +%F`)

# if warnings is populated, show them
[[ ! -z $warnings ]] && echo -e "\nBelow are warnings from pacman:\n\n$warnings\n\n"
