#! /bin/bash

# a script to check if the shell session we're in is an SSH session.
# you'd think it would be obvious, but not when all internal machines share dotfiles

YELLOW='\e[33m'
NOCOL='\e[0m'
# check for var
activeSSHCon=$(env | grep SSH_CLIENT)
if [[ -n $activeSSHCon ]]; then
  # scrub all of var except ip where we came from
  ipFrom=${activeSSHCon//*=}
  ipFrom=${ipFrom%% *}
  # cleaner than passing a var to awk
  # check if we know this ip from our ssh config
  hostnameFrom=$(grep $ipFrom $HOME/.ssh/config | awk '{print $3}')
  # print this info in a format PS1 recognizes
  printf "${YELLOW}[SSH:${hostnameFrom:=$ipFrom}->$(cat /etc/hostname)]${NOCOL}" || printf ""
fi
