#! /bin/bash

# This script utilizes xrandr to select the desired video output configuration and switches audio output accordingly

[[ -f $HOME/.shell_colors ]] && source $HOME/.shell_colors

exit_trap () {
  # capture each command via BASH_COMMAND so we can output it if there's a failure in exit_trap
  local lc="$BASH_COMMAND" rc=$?
  printf "${RED}Command ${YELLOW}$lc${RED} exited with code ${YELLOW}$rc${NOCOL}\n"
}

# if an error happens, invoke exit_trap and tell us what command failed
#trap exit_trap EXIT
#set -e

# define a query file to write xrandr output to
xrandr_query_file="/tmp/xrandr_query_$(echo ${RANDOM})"
#printf "${BLUE}query file:${NOCOL} $xrandr_query_file\n"

# if there is no query file, create one and make it sensible perms
if [[ ! -f ${xrandr_query_file} ]]; then
  touch ${xrandr_query_file}
  chmod 600 ${xrandr_query_file}
fi

# write the xrandr output to a file for parsing
xrandr_query=$(xrandr --query > ${xrandr_query_file})
# get which devices have status 'connected'
connectedDevices=($( awk '/ connected /{print $1}' ${xrandr_query_file} ))
# get the primary screen
primaryScreen=$(awk '/ primary /{print $1}' ${xrandr_query_file} )


echo -e "${BLUE}pre-remove connectedDevices:${NOCOL} ${connectedDevices[@]}"
printf "${BLUE}primary:${NOCOL} ${primaryScreen}\n"
printf "${BLUE}laptop:${NOCOL} ${primaryScreen}\n"
# determine all non-primary but connected screens
for screen in "${connectedDevices[@]}"; do
  echo "screen: $screen"
  if [[ "${screen}" == "${primaryScreen}" ]]; then
    echo "unsetting $screen"
    unset 'connectedDevices[i]'
  fi
done

# set some positions where the primary screen can be relative to the external screen
possibleRelPositions=( left-of right-of above below same-as )

echo -e "${BLUE}connectedDevices:${NOCOL} ${connectedDevices[@]}\n"
printf "${BLUE}primary:${NOCOL} ${primaryScreen}\n"
printf "${BLUE}laptop:${NOCOL} ${primaryScreen}\n"

[ -z $1 ] && read -p "Single or Multi display? " singleOrMultiMonitor || singleOrMultiMonitor=$1

if [[ $singleOrMultiMonitor == "s" ]]; then
  echo "Which screen would you like to use?"
  select whichScreen in "${connectedDevices[@]}" Exit;
  do
    case $whichScreen in
      Exit)
        printf '\n...Exiting, doing nothing...\n\n'
        break
        ;;
      *)
        printf "${BLUE}User selected ${YELLOW}$whichScreen${BLUE} as the screen to use${NOCOL}\n"
        discardedScreen=$(echo ${connectedDevices[@]/$whichScreen})
        xrandr --output $whichScreen --mode 1920x1080 --primary
        [ ! -z $discardedScreen ] && xrandr --output $discardedScreen --off
        xwallpaper --stretch $HOME/.pape.png 2&>/dev/null
        if [[ $whichScreen == *"HDMI"* ]]; then
          printf "${BLUE}Using ${YELLOW}HDMI${BLUE} audio\n"
          pacmd set-card-profile 0 output:hdmi-stereo
        else
          printf "${BLUE}Using ${YELLOW}primary screen${BLUE} audio\n"
          pacmd set-card-profile 0 output:analog-stereo
        fi
        notify-send -u normal -t 2000 "Moving display to $whichScreen"
        break
        ;;
    esac
  done

elif [[ $singleOrMultiMonitor == "m" ]]; then
  echo "Where do you want the primary screen relative to the external screen?"
  select primaryScreenRelPosition in "${possibleRelPositions[@]}" Exit;
    do
      case ${primaryScreenRelPosition} in
        Exit)
          printf '\n...Exiting, no changes made... \n\n'
          break
          ;;
        *)
          echo "Setting laptop screen ${primaryScreenRelPosition} external monitor"
          notify-send -u normal "Moving ${primaryScreen} ${primaryScreenRelPosition} external monitor"
          xrandr --output HDMI-2 --mode 1920x1080
          xrandr --output ${primaryScreen} --auto
          xrandr --output ${primaryScreen} --${primaryScreenRelPosition} HDMI-2
          xwallpaper --stretch ${HOME}/.pape.png
          chooseAudio
          generatei3MonitorConfig
          break
          ;;
      esac
    done
fi

rm ${xrandr_query_file}
