#! /bin/bash

resolution=($( xrandr -q | grep [0-9]x[0-9] | tail -n +2 | awk '{print $1}' ))

echo "Please select a resolution for SCREEN: "

select res in "${resolution[@]}" Exit;
do
	case $res in
		Exit)
			printf '\n...Exiting, no changes to resolution made... \n\n'
		       	break
			;;
		*)
			printf '\nChoosing res: %s\n' "$res"
			printf 'Setting SCREEN to %s'"$res"
			echo
			break
			;;
	esac
done
