#! /bin/bash

function vpnConnect {
#	nmcli c u $choice --ask
	nordvpn connect $country $city
}

function conUp {
	 nmcli c s | grep nord | grep $typeCon > /dev/null
}

vpnCountry=$( $1 | dmenu -p "Which country? (sw/ca/us):" )
#file=$( shuf $HOME/Network/${vpnCountry}TcpFiles )
#choice=$( echo ${file%%.ovpn*} | awk '{print $1}' )
#nmcli c u $choice --ask

nordvpn disconnect
city=$( shuf $HOME/Network/${vpnCountry}Cities | head -n 1 ) > /dev/null
if [ "$vpnCountry" == "sw" ];
then
	country="Switzerland"
	city="Zurich"
elif [ "$vpnCountry" == "ca" ];
then
	country="Canada"
elif [ "$vpnCountry" == "us" ];
then
	country="United_States"
elif [ "$vpnCountry" == "dis" ];
then
	nordvpn disconnect
else
	notify-send -u low -t 2500 "Choosing random server.."
fi
vpnConnect
