#! /bin/bash

choice=$( $1 | xrandr --query | grep -w "connected" | awk '{print $1}' | dmenu -p "Which device would you like audio played on? " )

if [ $choice == "eDP1" ]
then
	audioOutput="output:analog-stereo"
else
	audioOutput="output:hdmi-stereo-extra1"
fi

pacmd set-card-profile 0 $audioOutput
