#! /bin/bash

choice=($(xrandr --query | grep -w "connected" | awk '{print $1}'))
primaryScreen=$(xrandr --query | grep primary | awk '{print $1}')

select screenChoice in "${choice[@]}" Exit;
do
	case $screenChoice in
		Exit)
			printf '\n...Exiting, doing nothing...\n\n' && break ;;
		*)
			screenChoice=$screenChoice && break ;;
	esac
done

[[ $screenChoice == $primaryScreen ]] && audioOutput="output:analog-stereo" || audioOutput="output:hdmi-stereo-extra1"
pacmd set-card-profile 0 $audioOutput
