#! /bin/bash


songTime=($(cmus-remote -Q | awk '/duration|position/{print $2}'))
secRemaining=$(echo "${songTime[0]} - ${songTime[1]}" | bc -q)
#secRemaining=61
convertToMinutes=$(echo "$secRemaining / 60" | bc -ql)
[[ $convertToMinutes -lt 1 ]] && minutes='00' || minutes=${convertToMinutes%.*}
decimalMinutes=${convertToMinutes#*.}
decimalMinutesToSeconds=$(echo "0.${decimalMinutes:0:2} * 60" | bc -ql)
echo -E "$minutes:${decimalMinutesToSeconds:0:2}"

echo $convertToMinutes $minutes $decimalMinutes $decimalMinutesToSeconds
