#! /bin/bash

backupDir='$HOME/docs/test-dir'

syncFiles () {
	echo -e "\n\nSyncing over the following:"
	echo "rsync -av $backupDir $mountPoint" && \
		echo -e "\nIf done, unmount the device via:\nveracrypt --dismount $mountPoint"
	exit
}

mountPoint=($(lsblk | awk '/veracrypt/{print $7}'))

[ ! -v mountPoint ] && echo -e "\nDrive either not mounted and/or not opened via veracrypt. Find the partition with:\nlsblk | grep -v nvme\n\nThen run:\nveracrypt --mount /path/to/partition\n\nAfterwards, re-run this script" && exit

[[ ${#mountPoint[@]} -gt 1 ]] && \
	lsblk | awk '!/nvme/{print $1" "$4" "$7}' && \
	echo -e "\nPlease select the appropriate mountpoint based on the above info:" && \
	select mountPoint in "${mountPoint[@]}" Exit;
	do
		case $mountPoint in
			Exit)
				echo -e "\n...Exiting, nothing done...\n\n"
				stop=1 && break;;
			*)
				stop=0 && break;;
		esac
	done 

[ -v mountPoint ] && syncFiles
