#! /bin/bash

# if we're in the root or $HOME directory, bail due to size/time
[[ $PWD == / || $PWD == $HOME ]] && exit 4

# find .git dirs after $HOME/, ignoring errors if none found
gitDirs=($(find $(echo $PWD | cut -d/ -f1-4) -type d -name .git 2>/dev/null))

# if gitDirs isn't empty, search
if [ ${#gitDirs[@]} -gt 0 ]; then
  for a in ${gitDirs[@]}; do
  # if we're in a subdir of a git dir, exit
  [[ $PWD =~ ${a%/.git} ]] && exit 3
  done
fi
