#! /bin/bash

# This script adds, commits, and pushes the files from the present working
# directory to the corresponding github repository.

# Change to appropriate directory
cd $HOME/tools

# Perform the pull
git pull origin master

# Show the commit message, signaling a completed push
notify-send --expire-time=3000  "Tools pulled"


