#! /bin/bash

# This script adds, commits, and pushes the files from the present working
# directory to the corresponding github repository.

# Change to appropriate directory
cd $HOME/.config/.files 

# Generate the commit message using dmenu as the interface
commitMessage="$($1 | dmenu -i -p  "Dotfiles commit message?")"

# Perform the push
git add .
git commit -m "$commitMessage"
git push origin master

# Show the commit message, signaling a completed push
notify-send --expire-time=3000  "Dotfiles Commit Message: $commitMessage"

