#! /bin/bash

# Creates a Jira post report for an environment based on user inputs 

sadPath=~/repos/siteportal_ansible_deploy
postNotes=~/vmShared/post-docs/00-posting-notes.txt
postTemplate=~/vmShared/post-docs/jira-template-post-report.txt

# Read in variables
read -p "Env name: " ENV
read -p "Hostname: " HOST
read -p "Target IP: " IP
read -p "Ansible Platform: " UNIFIEDPLATFORM
read -p "Version FROM: " FROM
read -p "Version TO: " TO

outputPath=~/vmShared/post-docs/$ENV-jira-report.txt

sadTag=$(cd $sadPath && git describe)
sadBranch=$(cd $sadPath && git branch | awk '/\*/{print $2}')
unifiedApiVersion=$(sed -n "/$ENV/,/Unified API/{p; /Unified API/q}" $postNotes | grep -w 'Unified API')
unifiedAppsvrVersion=$(sed -n "/$ENV/,/Unified APPSVR/{p; /Unified APPSVR/q}" $postNotes | grep -w 'Unified APPSVR')
unifiedNgVersion=$(sed -n "/$ENV/,/Unified NG/{p; /Unified NG/q}" $postNotes | grep -w 'Unified NG')
gdfVersion=$(sed -n "/$ENV/,/GDF/{p; /GDF/q}" $postNotes | grep -w 'GDF')
snmpVersion=$(sed -n "/$ENV/,/SNMP/{p; /SNMP/q}" $postNotes | grep -w 'SNMP')
date=$(date "+%Y%m%d")

# Make the substitutions from the template and output those subs into the post report
echo "$(sed "s/\$ENV/$ENV/g; \
	s/\$HOST/${HOST^^}/g; \
	s/\$IP/$IP\/$ENV/g; \
	s/\$UNIFIEDPLATFORM/$UNIFIEDPLATFORM/g; \
	s/\$FROM/$FROM/g; \
	s/\$TO/$TO/g; \
	s/\$sadBranch/$sadBranch/g; \
	s/\$sadTag/$sadTag/g; \
	s/\$unifiedApiVersion/$unifiedApiVersion/g; \
	s/\$gdfVersion/$gdfVersion/g; \
	s/\$snmpVersion/$snmpVersion/g; \
	s/\$unifiedAppsvrVersion/$unifiedAppsvrVersion/g; \
	s/\$unifiedNgVersion/$unifiedNgVersion/g; \
	s/\$date/$date/g; " $postTemplate)" > $outputPath

# Also copy the report to the clipboard to post into Jira. 
echo -e "Template created for this post located at: \n $outputPath"
cat ~/vmShared/post-docs/$ENV-jira-report.txt | xclip -selection clipboard -i
echo "Copied report to clipboard.."
