#! /bin/bash

# Uses i3-msg to open cmus if there isn't one running already, otherwise pauses/plays the music per normal operation

# check if cmus is already running
# toggle pause if it is, otherwise launch a terminal running it
if pgrep -x "cmus" > /dev/null
then
  cmus-remote --pause
else
  i3-msg -t run_command "exec $TERMINAL -n cmus -e cmus" # launches cmus in scratchpad (see i3/config)
  cmus-remote --pause
fi
# explicitly exit 0 if we've made it this far
exit 0
