#!/bin/bash
# This is a script called in a Vim function to compile the current document. See vimrc.
# It depends on a program called pydflatex which can be found at: https://github.com/olivierverdier/pydflatex

file=$1
file=${file%.*}

#If a latex 'build' directory does not exist, create it. This helps keep the directory clean of all the compiled files.
if ! (ls | grep build* >/dev/null)
then
	mkdir build 
fi

#This helps keep the main directories clean of `unnecessary' files.
function moveLogs { 
	mv $file.aux build
	mv $file.fls build
	mv $file.log build
	mv $file.pdf build
}

#Check if a pdf of the file is already open. Zathura supports live-refreshing.
if ps -aux | grep -v grep | grep "$PDFVIEWER $PWD/build/$file.pdf"
then
	pydflatex $file.tex
	moveLogs
else
	pydflatex $file.tex
	moveLogs
	zathura $PWD/build/$file.pdf &
fi
