#! /bin/bash

# This was the precursor to dirParse, but only works for a single directory i.e. will only operate on files within 
# subdirectories. Will not go into directories of subdirectories. 

cd $PWD

typeFrom=m4a
typeTo=mp3

for a in */;
do dirName="echo $a";
	dirName=${dirName:5}
	cd "$dirName"

	for b in *.$typeFrom;
	do name=`echo "${b%.*}"`;
#		ffmpeg -i "$b" "${name}.$typeTo";
#		echo "Processing Files In $PWD..."
#		sleep .5s
	done
#	echo "Removing .m4a files from $PWD"
	rm *.$typeFrom
	cd ..
done

for c in *.$typeFrom;
do name=`echo "${c%.*}"`;
#	ffmpeg -i "$c" "${name}.$typeTo";
#	echo "Processing Files In $PWD..."
#	sleep .5s
done
#	echo "Removing .m4a files from $PWD"
rm *.$typeFrom

# Let me know it's done
#( speaker-test -t sine -f 500 )& pid=$! ; sleep 0.2s ; kill -9 $pid
