#! /bin/bash

if [ "$1" == "m" ]; then
	sshfs -p 8008 -o ServerAliveInterval=15 -o reconnect -o IdentityFile=~/.ssh/id_rsa dj@73.186.221.50:/home/dj/music $HOME/music
elif [ "$1" == "u" ]; then
	killall cmus 2>&1 /dev/null
	sleep .3
	fusermount3 -u $HOME/music
else
	echo "Incorrect Choice. Select 'u' or 'm'"
fi
