#! /bin/bash
# Mounts drives, ignoring anything sda so I don't accidentally unmount root...

#mountables=$( $1 | lsblk -o NAME,SIZE,TYPE,MOUNTPOINT -l | grep part | grep -v 'nvme' | dmenu -l 4 | awk '{print $1}' )
mountableDevices=($(lsblk -o NAME,SIZE,TYPE,MOUNTPOINT | grep -v nvme | awk '/part/{print $1}' | tr -d '└─'))
#mountPoint=$( udisksctl info -b /dev/$mountables | grep "MountPoints:" | awk '{print $2}' )

echo ${mountableDevices[@]}

select mountPoint in "${mountableDevices[@]}";
do
	case $mountPoint in
		*)
			[[ $(udisksctl info -b /dev/$mountPoint | awk '/MountPoints:/{print $2}') ]] && break;;

			
	esac
done




#if [ -z $mountPoint ]; then
#	udisksctl mount -b /dev/$mountables
#	notify-send -t 2500 "Mounting: $mountables"
#else
#	udisksctl unmount -b /dev/$mountables
#	notify-send -t 2500 "Unmounting: $mountables"
#fi
