#!/bin/bash

#Set default value such that audio plays through laptop
#x=1

# function to check if HDMI is connected
function HDMIConnected {
	! xrandr | grep "^HDMI-0" | grep disconnected
}

if HDMIConnected
then
  x=0
else
  x=1
fi

# Move the sink
pacmd set-default-sink $x
pacmd list-sink-inputs | grep index | while read line
do
pacmd move-sink-input `echo $line | cut -f2 -d' '` $x
done
