#!/bin/bash

#Set default value such that audio plays through laptop
#x=1

# function to check if HDMI is connected
function HDMIConnected {
	! xrandr | grep "^HDMI2" | grep disconnected
}

#pacmd set-default-sink 0

if HDMIConnected
then
  x=1
else
  x=0
fi

# Move the sink
pacmd list-sink-inputs | grep index | while read line
do
pacmd move-sink-input `echo $line | cut -f2 -d' '` $x
done
