#! /bin/bash

ls -R /home/tom/music 2>&1 > /home/tom/music/.musicLibraryCheck
newMusic=$(diff /home/tom/music/.musicLibrary /home/tom/music/.musicLibraryCheck)
[ -f /home/tom/.newMusicLocations ] && rm /home/tom/.newMusicLocations
notify-send -u critical "music cron has run"

#if [[ $newMusic ]]; then
#	notify-send -u critical "There is new music, don't forget to convert and sync. View locations at ~/.newMusicLocations"
#	echo "$newMusic" > /home/tom/.newMusic
#	sed -i -e '1~2d' -e 's/^> //g' /home/tom/.newMusic
#	while read a; do
#		echo -e "$(find /home/tom/music -iname "$a")" >> /home/tom/.newMusicLocations
#	done < /home/tom/.newMusic
#	notify-send -u critical "If certain you're up to date, move ~/music/.musicLibraryCheck to ~/music/.musicLibrary"
#fi
