#! /bin/bash

DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u)/bus && export DBUS_SESSION_BUS_ADDRESS

ls -R $HOME/music 2>&1 > $HOME/music/.musicLibraryCheck
newMusic=$(diff $HOME/music/.musicLibrary $HOME/music/.musicLibraryCheck)
[ -f $HOME/.newMusicLocations ] && rm $HOME/.newMusicLocations
[ -f $HOME/.newMusic ] && rm $HOME/.newMusic

if [[ $newMusic ]]; then
	notify-send -u critical "There is new music, don't forget to convert and sync. View locations at ~/.newMusicLocations"
	echo "$newMusic" > $HOME/.newMusic
	sed -i -e '1~2d' -e 's/^> //g' $HOME/.newMusic
	while read a; do
		echo -e "$(find $HOME/music -iname "$a")" >> $HOME/.newMusicLocations
	done < $HOME/.newMusic
	notify-send -u critical "If certain you're up to date, run: mv ~/music/.musicLibraryCheck ~/music/.musicLibrary"
fi
