#! /bin/bash

tempFile=$(mktemp)



echo "uname -a -m -p" | tee -a $tempFile && uname -a -m -p &>> $tempFile && \
echo lspci && lspci -vvv -nn | awk 'BEGIN {RS="\n\n"} /Ethernet controller|Network controller/ {print $0}' &>> $tempFile && \
echo lsmod && lsmod &>> $tempFile && \
echo ip && ip &>> $tempFile && \
echo ip -a && ip -a &>> $tempFile && \
echo iwconfig && iwconfig &>> $tempFile && \
echo rfkill && rfkill list &>> $tempFile && \
echo iwlist && sudo iwlist `awk '/IEEE/ {print $1}' $tempFile` scan &>> $tempFile && \
echo resolv.conf && cat /etc/resolv.conf &>> $tempFile && \
#echo route && route -n &>> $tempFile && \
echo ping router && ping -c 1 `route | awk '/default/ {print $2}'` &>> $tempFile && \
echo ping dns server && ping -c 1 `awk '/nameserver/ {print $2}' /etc/resolv.conf | head -n 1` &>> $tempFile && \
echo ping using ip && ping -c 1 138.201.81.199 &>> $tempFile && \
echo ping using dns && ping -c 1 archlinux.org &>> $tempFile

#head -n 99999 /tmp/*.topdowntom
