#! /bin/bash

# from https://designprincipia.com/how-to-open-a-new-terminal-on-the-current/
# slightly modified TERINAL variable for my usage

# gets the currently focused window's id
current_focused_window_id=$(xprop -root -f _NET_ACTIVE_WINDOW 0x " \$0\\n" _NET_ACTIVE_WINDOW | awk "{print \$2}")

# get the tile for the current window
window_title=$(xprop -id $current_focused_window_id | sed -ne 's/WM_NAME(UTF8_STRING) = "\(.*\)"/\1/p')

# in my set up the title looks like "user@machine:path", this line uses sed to graph the path only after :
preferred_cwd=$(echo $window_title | sed -e 's/.*://')

# expand ~
preferred_cwd=${preferred_cwd//\~/$HOME}

# if path points to a valid directory, pass it to gnome-terminal
[[ -d "$preferred_cwd" ]] && $TERMINAL -e cd $preferred_cwd
