#! /bin/bash

# The specifics of this naming convention is a product of how I save music files and will vary depending on your needs.
# This changes the form: /home/user/music/Artist/Album/Song.filetype ---> Artist - Song

artist=$(cmus-remote -Q | awk '/ artist / {$1=$2=NULL; print}')
song=$(cmus-remote -Q | awk '/title/ {$1=$2=NULL; print}' | cut -d'.' -f1) # append Artist - Song
playing="$artist - $song"
playerStatus="$(cmus-remote -Q | awk '/status/{print $2}')" # get player status
# if artist and track length greater than 60, truncate it
[[ ${#playing} -gt 60 ]] && playing="${playing:0:60}..."

if [ $playerStatus = "playing" ] || [ $playerStatus = "paused" ]; then
	echo $playing && echo # define script output && set blank first echo statement for i3blocks
	[[ $playerStatus = "playing" ]] && echo "#e69809" || echo "#b3b3b3" # if playing orange, paused grey
	pkill -SIGRTMIN+1 i3blocks
else
	echo "" # if cmus not running, display nothing
fi
