#! /bin/bash

# The specifics of this naming convention is a product of how I save music files and will vary depending on your needs. 
# This changes the form: /home/user/Music/Artist/Album/Song.filetype ---> Artist - Song

file="$(cmus-remote -Q | sed -n '2p' | awk '{$1=""; print $0}' | cut -d' ' -f 2-)"

artist="${file##*music/}" # remove everything up through Music/
artist="${artist%%/*}" # remove everything between $artist and through to the last /
song="${file##*/}" # remove everything up through the last /
song="${song%.*}" # remove the filetype .filetype
playing="$artist - ${song}" # append Artist - Song

if [ $(cmus-remote -Q | grep status | awk '{print $2}') = "playing" ]; then
	echo $playing
	echo && echo "#e69809"
	pkill -SIGRTMIN+1 i3blocks
else
	echo $playing
	echo && echo "#b3b3b3"
	pkill -SIGRTMIN+1 i3blocks
fi
