#! /bin/bash

# Obtain IP address if online, and indicate if VPN tunnels are up

# Exit this script if the site is unreachable, which happens periodically
[[ `curl --write-out '%{http_code}' --silent --output /dev/null ifconfig.me` != 200 ]] && { echo "ifconfig.me error"; exit 1; } || \

testOnline
if [ $? -eq 0 ]; then
	if [ "$(nmcli c s | grep tun)" ]; then
   echo "T:`protonvpn-cli status | awk '/Server:/ || /IP:/ {print " "$2}' | tr -d '\n'`" && echo && echo \#3cb371
  else
   echo `curl ifconfig.me` && echo && echo \#b22222
  fi
fi
