#! /bin/bash

# Obtain IP address if online, and indicate if VPN tunnels are up

if [ "$(ping -c1 8.8.8.8)" ]; then
	[[ "$(nmcli c s | grep tun)" ]] && echo "T: `curl ifconfig.me`" || echo `curl ifconfig.me`
fi
