#!/bin/sh

outputPath=$HOME/pix
loop=1
pgrep -x picom && killall picom

while [ "$loop" -eq 1 ]
do

loop=0
typechoice="$(echo -e "selection\nfull\nwindow" | dmenu -i -p Screenshot)"

case "$typechoice" in
        "")
                exit ;;
        "selection")
                copychoice="$(echo -e "yes\nno\nback" | dmenu -i -p "Copy to clipboard?")"
                case "$copychoice" in
                        "")
                                exit ;;
                        "yes")
                                scrot -s $outputPath/screenshot-$(date +%s).png -e 'xclip -selection c -t image/png < $f' ;;
                        "no")
                                scrot -s $outputPath/screenshot-$(date +%s).png ;;
                        "back")
                                loop=1 ;;
                esac ;;
        "full")
                copychoice="$(echo -e "yes\nno\nback" | dmenu -i -p "Copy to clipboard?")"
                case "$copychoice" in
                        "")
                                exit ;;
                        "yes")
                                scrot $outputPath/screenshot-$(date +%s).png -e 'xclip -selection c -t image/png < $f' ;;
                        "no")
                                scrot $outputPath/screenshot-$(date +%s).png ;;
                        "back")
                                loop=1 ;;
                esac ;;
        "window")
                copychoice="$(echo -e "yes\nno\nback" | dmenu -i -p "Copy to clipboard?")"
                case "$copychoice" in
                        "")
                                exit ;;
                        "yes")
                                scrot -u $outputPath/screenshot-$(date +%s).png -e 'xclip -selection c -t image/png < $f' ;;
                        "no")
                                scrot -u $outputPath/screenshot-$(date +%s).png ;;
                        "back")
                                loop=1 ;;
                esac ;;
esac

done

picom &
