#! /bin/bash

# A simple system temperature module for polybar

#temp=$(cat /sys/class/thermal/thermal_zone0/temp)
temp=$( sensors | grep Tdie | awk '{print $2}' )
tempHigh=${temp##*+}
red="%{F#b6465f}"
gold="%{F#e89709}"

#echo $tempHigh
echo -e "${gold}${tempHigh}${F-}"
