#! /bin/bash
# Restarts the urxvt daemon to apply the new color changes. Must have the config-reload perl extension enabled.
# See https://github.com/regnarg/urxvt-config-reload for details.

themeChoice=$($1 | ls -A $HOME/.colors/ | dmenu -l 10 -p "Which Theme Would you Like?:")

cat $HOME/.colors/$themeChoice > $HOME/.Xres-theme && xrdb -load $HOME/.Xres-theme && kill -1 `pidof urxvtd` && i3-msg restart
