#! /bin/bash

# Run this as root to change trackpoint sensitivity
if [[ $EUID != 0 ]] ; then
  echo This must be run as root!
  exit 1
fi

echo -n 200 > /sys/devices/platform/i8042/serio1/serio2/sensitivity
echo -n 200 > /sys/devices/platform/i8042/serio1/serio2/speed
