#! /bin/bash
# Work in progress

numCores=$( cat /proc/cpuinfo | grep siblings | head -n 1 | awk '{print $3}' )
cpuUsage=$( cat /proc/cpuinfo | grep "cpu MHz" | awk '{print $4}' )
notify-send -t 3000 "$cpuUsage"
avgUsage=$( echo "$cpuUsage" | head -n 1 )
av=$( echo "$cpuUsage" | head -n 2 | tail -n 1)

i=1
while [ "$i" -le "$numCores" ]; do
	cpuUsage=$( cat /proc/cpuinfo | grep "cpu MHz" | awk '{print $4}' | head -n 1 )
	echo $cpuUsage | awk '{print $1}'
	(( i++ ))
	sleep .5s
done


#notify-send -t 2000 "$avgUsage     $av"
#echo $cpuUsage
