#! /bin/bash

# A more accurate memory module for polybar
blue="%{F#6992c5}"

# Get the memory
mem=$(free -m | grep Mem: | awk '{print $3}')

if [ "${#mem}" -gt 3 ]; then
	echo "${mem%???}.${mem:1:2} GB" # regex and color formatting
	echo && echo "#0066ff"
else
	echo "$mem MB"
	echo && echo "#0066ff"
fi
