#! /bin/bash
#cvt 1920 1080

connectedScreen=$( xrandr | grep -w connected | awk '{print $1}' )
xrandr --newmode `cvt 1920 1080 | tail -n1 | cut -d' ' -f2-`
xrandr --addmode $connectedScreen `cvt 1920 1080 | tail -n1 | awk '{print $2}'`
xrandr --output $connectedScreen --mode `cvt 1920 1080 | tail -n1 | awk '{print $2}'`

#VBoxClient --clipboard
