#! /bin/bash

# Check if spool tempfile exists, and make one if not
[ ! -f /tmp/tmp.*spool ] && mktemp --suffix=spool 1>/dev/null
[ ! -f /tmp/tmp.*mpvout ] && mktemp --suffix=mpvout 1>/dev/null

# Grab the file state
spoolFile=$(ls /tmp/tmp.*spool)
mpvoutFile=$(ls /tmp/tmp.*mpvout)

if [ -n "$1" ];
then
  echo input given, adding item to next item in of spool file
  # Remove duplicates and ensure valid hyperlinks before proceeding
  echo "$(grep https $spoolFile | uniq)" > $spoolFile
  input="$1"
else
  echo no input given, grabbing from spool file
  # Write current clipboard item to spool file
  echo $(xclip -o) >> $spoolFile
  # Remove duplicates and ensure valid hyperlinks before proceeding
  echo "$(grep https $spoolFile | uniq)" > $spoolFile
  input="$(head -n1 $spoolFile)"
fi

# show me what im playing
echo input: $input

# if there's no mpv already playing, start playing from the spoolfile as a playlist
if [ ! $(pgrep mpv) ]; then
	mpv --playlist=$spoolFile &> $mpvoutFile &
#	[ $(file $spoolFile | awk '{print $2}') != "empty" ] && mpv --playlist=$spoolFile &> $mpvoutFile &
fi

# until i see "Exiting..." in the mpv stdout, sleep
until grep -q -i "Exiting..." $mpvoutFile
do
	echo "..."
	sleep 1
done

sed -i 1d $spoolFile
rm $mpvoutFile
exit 0

## Add the copied video URL to the file
#echo $(xclip -o) >> $spoolFile
## Remove duplicates before proceeding
#echo "$(cat $spoolFile | uniq)" > $spoolFile
#
#if [ ! $(pgrep mpv) ]; then
#	mpv --playlist=$spoolFile
#	sed -i 1d $spoolFile
#	[ $(file $spoolFile | awk '{print $2}') != "empty" ] && mpv --playlist=$spoolFile
#else
#	exit 0
#fi
