#! /bin/bash

# This script downloads yt videos to a dir and notifies the user on start and completion
videoDir=$HOME/videos/yt
failedURLs=/tmp/failed_video_urls
link=${1}

download () {
  filename=$(/usr/bin/yt-dlp "$link" --print filename --skip-download 2> /dev/null)
  randomVidId=$RANDOM
  notify-send -u low "Downloading: $filename"
  tmux new-session -d -s $randomVidId
  tmux send-keys -t $randomVidId "cd $videoDir; ${downloadCommand} '${link}' && { notify-send -u normal "Completed: $filename"; exit; } || { notify-send -u critical "failed: $filename - $randomVidId"; }" Enter;

}

if [[ "$1" =~ "odysee.com" ]]; then
  downloadCommand='/usr/bin/yt-dlp'
  download & disown
elif [[ "$1" =~ "youtube" ]]; then
  downloadCommand="/usr/bin/yt-dlp -f 'bv*[height<2160]+bestaudio'"
  download & disown
fi
