#! /bin/bash

# Gets the volume percentage
vol=$(pamixer --get-volume)
muted=$(pamixer --get-mute)

# Echo the volume to the path the polybar module volLevel looks to cat. 
if [ $muted == "true" ]; then
	echo "Muted" > $HOME/.config/polybar/volLevel
else
	echo "$vol%" > $HOME/.config/polybar/volLevel
fi

# Trigger the polybar ipc module
polybar-msg hook volLevel 1

