#! /bin/bash

# Gets the volume percentage
vol=$(pamixer --get-volume)
muted=$(pamixer --get-mute)

# Echo the volume to the path the polybar module volLevel looks to cat.
if [ $muted == "true" ]; then
	echo "Muted"
	echo && echo "#ff0000"
else
	echo "$vol%"
	echo && echo "#cccccc"
fi
