#! /bin/bash

#This script saves pywal themes I like and might want to use again.
#See polybar config for polybar-menu implementation

outputDirectory=$HOME/.config/wal/colorschemes/likedSchemes

if [ $1 == "save" ]; then
	colorschemeName=$( $1 | dmenu -p "What should this colorscheme be called?" ) 
	cat $HOME/.cache/wal/wal > $outputDirectory/$colorschemeName
elif [ $1 == "load" ]; then
	getScheme=$( $1 | ls $HOME/.config/wal/colorschemes/likedSchemes | dmenu -l 10 )
	wal -a 95 -i $( cat $outputDirectory/$getScheme )
elif [ $1 == "new" ]; then
	wal -a 95 -i $HOME/pictures/miscWG
elif [ $1 == "inplace" ]; then
	current=$( cat .fehbg | awk '{print $3}' | tail -n 1 | sed 's/.//;s/.$//' )
	wal -a 95 -i $current
fi
